### ISSUE TITLE
The Ads Lab Integration is not working

### ISSUE THREAD

**Issue by AMGadmin** [merchantprotocol/shadowmailer-support#7] opened 2022-08-19 20:50 UTC
The Ads Lab Integration is not working with Shadowmailer
![image](https://user-images.githubusercontent.com/17806760/185704956-0a3bccf1-0d6c-493c-b457-63117f5798c4.png)

**Comment by jonathonbyrdziak** [comment] 2022-08-20 17:32
@alancarvalho We need to escalate this error. It's happening within the matomo-identity-resolution platform when creating an integration to connect to shadowmailer.

**Comment by jonathonbyrdziak** [comment] 2022-08-20 17:38
# How To Recreate this error

__Date:__ August 20, 2022

__Author:__ Jonathon Byrdziak

***

### 1. [Go to Sign in - Matomo](https://app.theadslab.io/)
Enter your credentials for matomo


### 2. Click on Sign In
![Step 2 screenshot](https://images.tango.us/public/screenshot_fa32a35c-33ac-4fd3-9f08-c74094408815.png?crop=focalpoint&fit=crop&fp-x=0.6177&fp-y=0.4548&fp-z=2.7907&w=1200&ar=1920%3A897)


### 3. Click on the Gear icon in the top right
![Step 3 screenshot](https://images.tango.us/public/screenshot_d7b1111e-a16b-4c03-b938-baca8d243fc8.png?crop=focalpoint&fit=crop&fp-x=0.9328&fp-y=0.0346&fp-z=3.1463&w=1200&ar=1920%3A897)


### 4. Click on Integrations
![Step 4 screenshot](https://images.tango.us/public/screenshot_80973931-8afe-453e-bc67-bbba3058c81d.png?crop=focalpoint&fit=crop&fp-x=0.0583&fp-y=0.3283&fp-z=2.4000&w=1200&ar=1920%3A897)


### 5. Click on Manage
![Step 5 screenshot](https://images.tango.us/public/screenshot_cd3d098e-379e-47d3-aabc-c8a7ff950e24.png?crop=focalpoint&fit=crop&fp-x=0.0583&fp-y=0.3724&fp-z=2.4000&w=1200&ar=1920%3A897)


### 6. Click on CREATE NEW INTEGRATION
![Step 6 screenshot](https://images.tango.us/public/screenshot_5e5c8cf9-1595-455b-9e93-068b07ddf803.png?crop=focalpoint&fit=crop&fp-x=0.1977&fp-y=0.4716&fp-z=2.3674&w=1200&ar=1920%3A897)


### 7. Name this integration
![Step 7 screenshot](https://images.tango.us/public/screenshot_e78d2e53-163e-4c09-afd0-a06a359186f7.png?crop=focalpoint&fit=crop&fp-x=0.3005&fp-y=0.4699&fp-z=1.6244&w=1200&ar=1920%3A897)


### 8. Choose the Integration Type: Shadow Mailer
![Step 8 screenshot](https://images.tango.us/public/screenshot_b2af4b98-9322-4ec1-a06f-c31c1c8b78c9.png?crop=focalpoint&fit=crop&fp-x=0.3005&fp-y=0.5914&fp-z=1.6244&w=1200&ar=1920%3A897)


### 9. Select the website to sync
![Step 9 screenshot](https://images.tango.us/public/screenshot_55c09ba3-991b-4602-a55e-3a925b1eff20.png?crop=focalpoint&fit=crop&fp-x=0.3005&fp-y=0.6204&fp-z=1.6244&w=1200&ar=1920%3A897)


### 10. Enable this integration
![Step 10 screenshot](https://images.tango.us/public/screenshot_b5dc7c2c-a84e-457d-81ea-5f520369c277.png?crop=focalpoint&fit=crop&fp-x=0.1461&fp-y=0.8913&fp-z=3.2598&w=1200&ar=1920%3A897)


### 11. Click on Save & Step Two
![Step 11 screenshot](https://images.tango.us/public/screenshot_58c288de-9a47-433a-a7be-0bfd8c54057b.png?crop=focalpoint&fit=crop&fp-x=0.1831&fp-y=0.9654&fp-z=2.5430&w=1200&ar=1920%3A897)


### 12. Enter your API token from Shadow Mailer
![Step 12 screenshot](https://images.tango.us/public/screenshot_cf9e1ee0-5189-4d87-89a0-9a420cbfd252.png?crop=focalpoint&fit=crop&fp-x=0.3005&fp-y=0.5190&fp-z=1.6244&w=1200&ar=1920%3A897)


### 13. Click on Test & Continue
![Step 13 screenshot](https://images.tango.us/public/screenshot_19d321df-a6db-4fad-a217-fe61aaab86bf.png?crop=focalpoint&fit=crop&fp-x=0.1831&fp-y=0.6154&fp-z=2.5430&w=1200&ar=1920%3A897)


### 14. See the error provided
![Step 14 screenshot](https://images.tango.us/public/image_2dd40e26-99e7-4bbf-a099-1d9ad691fc48.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&fp-z=1.0000&w=1200&ar=1876%3A240)

**Comment by development0261** [comment] 2022-08-23 05:26
@jonathonbyrdziak ,

In step 12, I need to set an API token. So do I need to create account on https://app.shadowmailer.com/users/register ?

**Comment by jonathonbyrdziak** [comment] 2022-08-23 06:22
@AMGadmin we're having difficulty recreating the error. When we test it completed successfully.

We'll keep trying, is there anything additional you can add to help us debug?

**Comment by AMGadmin** [comment] 2022-08-23 14:46
Every time I try it gives the same error

**Comment by jonathonbyrdziak** [comment] 2022-08-24 05:41
Ok I'll have to debug your account directly.

Can you give your integration a unique name and provide it to me.

**Comment by AMGadmin** [comment] 2022-08-24 14:17
The unique name is: AMGNES

**Comment by development0261** [comment] 2022-08-29 04:15
Hey. 

I've tested this issue multiple times, but I'm not able to recreate this issue. It's working fine at my side.

**Comment by AMGadmin** [comment] 2022-08-29 15:47
I'm using a webhook now because i couldnt get this to work. Thanks

**Comment by alancarvalho** [comment] 2022-09-01 22:57
Hi @development0261 

I recorded my screen showing how to reproduce it.

[Integration Issue](https://user-images.githubusercontent.com/5169108/188026196-e2c0db6c-cf79-4a6d-ac2a-6ad46075e96a.webm)

It also happens for new integrations created.
Please let me know if you have any questions.

Regards,

**Comment by tusharlogix** [comment] 2022-09-05 04:43
Hey @alancarvalho ,

Okay, I'll check on this way and update you on same.

Thanks.

**Comment by tusharlogix** [comment] 2022-09-05 14:38
Hey @alancarvalho ,

I tried the way you showed in your video, but still, I'm not facing an issue on my side. 
I've tried editing the existing as well as creating new integration as per the initial integration, but still, it gives me success every time.

Here is a video recording that shows you what is happening on my side. : https://www.loom.com/share/6a30485d8eea43f2a21425e3b1fcc0fd

According to the error **We did not receive a successful response from the API credentials you provided.**
I think the issue is not at **Maotmo** side, it is from the API in **shadowmailer**. There might be something missing in your Shadowmailer account or any permisison-related issue which is not sending the expected response and that's why it is showing such kind of error.

Can you figure out if there is any permission-related or access-related thigns in your shadowmailer account because the response is sent back to Matomo from shadow mailer only and that is based on the API key that we're providing?

**Comment by alancarvalho** [comment] 2022-09-06 02:19
Hi @tusharlogix 

Please add some logs to \Piwik\Plugins\IdentityResolution\Services\Shadowmailer::testConnection
I don't have perms to merge my own PRs. If possible try to log request url + params too.
Like we have for other error messages on Diagnostic > Log Viewer

---

I used Postman to test connection to https://app.shadowmailer.com/api/v1/lists?api_token=... and https://api.shadowmailer.com/api/v1/lists?api_token=...

For both cases I received a 200 response.

**Comment by tusharlogix** [comment] 2022-09-06 03:45
Hey @alancarvalho ,

I also checked in postman and it gives me success response.

**Comment by tusharlogix** [comment] 2022-09-06 14:30
Hey @alancarvalho ,

I've simply added the debug log and displayed the response of API in that.

**Comment by tusharlogix** [comment] 2022-09-06 15:10
I've added the debug log in \Piwik\Plugins\IdentityResolution\Services\Shadowmailer::testConnection which will show the whole response if success, otherwise log as error if failed.

I tried to check the logs on my local machine, was not able to find that anywhere. The log configuration is below in localhostconfig.ini.php
```
[log]
log_writers[] = "file"
logger_file_path = "error_debugging_log.log"
```

but there is no file named error_debugging_log.log in the project. You might able to check on server as there configurations might be different. Also please let me know how can I check the log on my local machine.

Thanks.

**Comment by alancarvalho** [comment] 2022-09-06 16:02
Hi @tusharlogix 

As I said previously, add logic to collect API response and log them to Diagnostic > Log Viewer: https://prnt.sc/QFWiSCCQyJT3

Commit and create a PR. After it, I will push to Live and check which message we are receiving from API.

Please focus on that request.

**Comment by tusharlogix** [comment] 2022-09-07 13:39
Hey @alancarvalho ,

I've added the warning logs for success response and error both. The system doesn't allow us to log other levels like info, error, etc. 

I've pushed the code. The PR seems already created by you so I've added the comment there also.

**Comment by tusharlogix** [comment] 2022-09-08 04:18
Hey @alancarvalho ,

Did you find any logs on live server??

**Comment by alancarvalho** [comment] 2022-09-08 23:38
Hi @jonathonbyrdziak 

Please enabled log writer in database. We need it to debug this issue. You can disable it later.

> No supported log writer configured
If one was configured in the past, you can still view old logs but new ones won't be shown. Read more about [how to configure a supported log writer](https://piwik.org/faq/troubleshooting/faq_115/). Supported are: file, database

CC: @tusharlogix

**Comment by alancarvalho** [comment] 2022-09-14 04:15
Hi @tusharlogix 

The issue was:
> Notice - A non well formed numeric value encountered
0: core/Changes/Model.php(140)
1: core/Changes/UserChanges.php(48)

Value was: 'idchange_last_viewed' => string '0000-00-00 00:00:00' (length=19)
Must be NULL or integer.

Fix: if not int, set it as NULL.

> Response from API : {"statusCode":false,"errorMessage":false,"body":null}

Fix: endpoint modified from app. to api.

Released to production.

**Results:**
https://prnt.sc/9_C-4qw-K-I8

**Comment by alancarvalho** [comment] 2022-09-14 04:16
Hi @AMGadmin 

This issue was fixed. Please let we know if you have any issue.

Closing task.

CC: @jonathonbyrdziak

**Closed as completed by alancarvalho** 2022-09-14 04:16 UTC
Labels: bug
